version: '3'

services:
    server-wishlist-tracker:
        image: ubuntu:lasted
        build: .
        container_name: wishlist-tracker
        restart: on-failure
        ports:
            - 8001:80
        volumes:
            - ./files:/home
        networks:
            - net-wishlist-tracker

networks:
    net-wishlist-tracker:
        driver: bridge
